version: '3'

services:
  database:
    image: mariadb
    container_name: database
    environment:
      MARIADB_ROOT_PASSWORD: L3dK1ll+
      MARIADB_DATABASE: accountant
      MARIADB_USER: accountant_web
      MARIADB_PASSWORD: L3dK1ll+
    ports:
      - 3333:3306
    volumes:
      - "./database/accountant_schema.sql:/docker-entrypoint-initdb.d/1.sql"
    networks:
     - backendNetwork

  backend:
    build: ./back/
    container_name: backend
    ports:
      - 8080:8080
    depends_on:
      - database
    volumes:
      - ./back/build/libs/accountant-0.0.1-SNAPSHOT.jar:/application.jar
    networks:
      - backendNetwork
      - frontendNetwork

  frontend:
    build: ./front/
    container_name: frontend
    ports: 
      - 80:80
    depends_on:
      - backend
    volumes:
      - ./front/dist/accountant/browser:/usr/share/nginx/html
    networks:
      - frontendNetwork

volumes:
  accountant_workspace_volume:

networks:
  backendNetwork:
  frontendNetwork: