
export enum EnumAccountantExceptionType {
	MALFORMED_REQUEST =				'MALFORMED_REQUEST',
	RESOURCE_NOT_FOUND =			'RESOURCE_NOT_FOUND',
	INSUFFICIENT_FUNDS =			'INSUFFICIENT_FUNDS',
	TRANSACTION_NOT_SUPPORTED =		'TRANSACTION_NOT_SUPPORTED',
	INTERNAL_SERVER_ERROR =			'INTERNAL_SERVER_ERROR',
}
